// src/lib/info/zh-cn/contactData.ts
// 联系我们页面的简体中文数据

export const zhCN = {
  title: '联系我们',
  intro1: '感谢您使用 24Watchin。如对本网站有任何意见、建议或咨询事项，请通过下方表单与我们联系。',
  intro2: '我们受理关于文章内容的意见与指正、更正通知、著作权与转载相关咨询，以及广告刊登与合作相关洽谈等事项。',
  beforeTitle: '联系前请确认以下事项',
  before1: '根据咨询内容、咨询数量、确认情况及其他相关情况，我们可能需要一定时间回复，或可能无法逐一回复。',
  before2: '于周六、周日、法定节假日及年末年初收到的咨询，可能会在下一营业日或之后进行确认。',
  before3: '对于本网站回复内容，请勿擅自转载、引用或再次分发。',
  before4: '对于仅以营销、招揽或宣传为目的之来信，我们可能无法予以回复。',
  privacyTitle: '关于个人信息的处理',
  privacyText: '您在联系表单中填写的信息，将用于回复咨询、确认内容、在必要时与您联系，以及与上述事项相关的其他附随目的。详情请参阅',
  privacyLink: '隐私政策',
  privacyPath: '../privacy/',
  privacyEnd: '。',
  formTitle: '联系表单',
  typeLabel: '咨询类型',
  typePlaceholder: '请选择',
  typeOptions: ['关于文章内容的意见与指正', '更正通知', '关于版权与转载的咨询', '关于广告投放与合作的咨询', '其他'],
  nameLabel: '姓名',
  namePlaceholder: '示例：王伟',
  emailLabel: '可联系的电子邮箱地址',
  emailPlaceholder: '示例：example@email.com',
  companyLabel: '公司名称・团体名称',
  companyPlaceholder: '示例：〇〇股份有限公司',
  subjectLabel: '主题',
  subjectPlaceholder: '示例：关于文章',
  urlLabel: '相关页面 URL',
  urlPlaceholder: '示例：https://24watchin.com/...',
  urlNote: '如系针对文章或页面的咨询，请填写相关 URL。',
  messageLabel: '咨询内容',
  messagePlaceholder: '请尽可能具体填写。',
  agreementText: '关于您所填写信息的处理方式，我已确认隐私政策并表示同意。',
  submitBtn: '提交',
  sending: '正在提交...',
  required: '必填',
  optional: '选填',
  successTitle: '您的咨询已收到。',
  successText: '我们将在确认内容后，视需要与您联系。',
  errorText: '发送失败。请稍后再试。',
};
