// src/lib/info/ja/contactData.ts

export const contactData = {
  ja: {
    title: 'お問い合わせ',
    description: '24Watchinへのお問い合わせはこちらから。記事の訂正・転載・著作権などもお気軽にどうぞ。',
    intro1: '24Watchinをご利用いただきありがとうございます。当サイトに関するご意見、ご感想、お問い合わせは、下記フォームよりご連絡ください。',
    intro2: '記事内容に関するご意見・ご指摘、訂正のご連絡、著作権・転載に関するお問い合わせ、広告掲載・提携に関するご相談などを受け付けています。',
    beforeTitle: 'お問い合わせの前にご確認ください',
    before1: 'お問い合わせの内容、件数、確認状況その他の事情により、回答までお時間をいただく場合や、回答を差し上げられない場合があります。',
    before2: '土曜、日曜、祝日、年末年始にいただいたお問い合わせは、翌営業日以降の確認となる場合があります。',
    before3: '当サイトからの回答内容について、無断で転載、引用、再配布することはご遠慮ください。',
    before4: '営業・勧誘・宣伝のみを目的とした送信については、回答いたしかねる場合があります。',
    privacyTitle: '個人情報の取り扱いについて',
    privacyText: 'お問い合わせフォームにご入力いただいた情報は、お問い合わせへの対応、内容の確認、必要なご連絡その他これらに付随する目的のために利用します。詳細については',
    privacyLink: 'プライバシーポリシー',
    privacyEnd: 'をご確認ください。',
    formTitle: 'お問い合わせフォーム',
    typeLabel: 'お問い合わせの種類',
    typePlaceholder: '選択してください',
    typeOptions: ['一般のお問い合わせ', '記事内容に関するご意見・ご指摘', '訂正・修正のご連絡', '著作権・転載・引用に関するお問い合わせ', '画像・写真・掲載素材に関するお問い合わせ', '個人情報の取り扱いに関するお問い合わせ', '広告掲載・提携に関するお問い合わせ', 'その他'],
    nameLabel: 'お名前',
    namePlaceholder: '例：山田 太郎',
    emailLabel: '連絡可能なメールアドレス',
    emailPlaceholder: '例：example@email.com',
    companyLabel: '会社名・団体名',
    companyPlaceholder: '例：株式会社〇〇',
    subjectLabel: '件名',
    subjectPlaceholder: '例：記事について',
    urlLabel: '対象ページURL',
    urlPlaceholder: '例：https://24watchin.com/...',
    urlNote: '記事やページについてのお問い合わせの場合は、該当URLをご記入ください。',
    messageLabel: 'お問い合わせ内容',
    messagePlaceholder: 'できるだけ具体的にご記入ください。',
    agreementText: 'ご入力いただいた情報の取り扱いについて、プライバシーポリシーを確認し、同意します。',
    submitBtn: '送信する',
    sending: '送信中...',
    required: '必須',
    optional: '任意',
    successTitle: 'お問い合わせを受け付けました。',
    successText: '内容を確認のうえ、必要に応じてご連絡いたします。',
    errorText: '送信に失敗しました。時間をおいて再度お試しください。',
  },
  en: {
    title: 'Contact',
    description: 'Contact 24Watchin here.',
    intro1: 'Thank you for using 24Watchin. Please use the form below to contact us.',
    intro2: 'We accept inquiries about article content, corrections, and more.',
    beforeTitle: 'Before You Contact Us',
    before1: 'We may not be able to respond to every message.',
    before2: 'Inquiries on holidays will be addressed on the next business day.',
    before3: 'Please do not reprint our responses without permission.',
    before4: 'Promotional messages may not receive a response.',
    privacyTitle: 'Privacy',
    privacyText: 'Your info will be used to respond. See our',
    privacyLink: 'Privacy Policy',
    privacyEnd: '.',
    formTitle: 'Contact Form',
    typeLabel: 'Type of Inquiry',
    typePlaceholder: 'Please select',
    typeOptions: ['General Inquiry', 'Feedback', 'Correction', 'Other'],
    nameLabel: 'Your Name',
    namePlaceholder: 'e.g. John Smith',
    emailLabel: 'Email Address',
    emailPlaceholder: 'e.g. example@email.com',
    companyLabel: 'Company',
    companyPlaceholder: 'Example Inc.',
    subjectLabel: 'Subject',
    subjectPlaceholder: 'About an article',
    urlLabel: 'Page URL',
    urlPlaceholder: 'https://...',
    urlNote: 'Include the URL if applicable.',
    messageLabel: 'Message',
    messagePlaceholder: 'Describe your inquiry.',
    agreementText: 'I agree to the Privacy Policy.',
    submitBtn: 'Send',
    sending: 'Sending...',
    required: 'Required',
    optional: 'Optional',
    successTitle: 'Received',
    successText: 'We will get back to you if needed.',
    errorText: 'Failed to send.',
  },
  'zh-cn': {
    title: '联系我们',
    description: '在这里联系24Watchin。',
    intro1: '感谢使用24Watchin。请使用下方表单联系我们。',
    intro2: '我们接受有关文章内容、更正等的查询。',
    beforeTitle: '联系前请确认',
    before1: '我们可能无法回复所有消息。',
    before2: '节假日的查询将在下一个工作日处理。',
    before3: '未经许可，请勿转载我们的回复。',
    before4: '推销信息可能不会收到回复。',
    privacyTitle: '隐私',
    privacyText: '您的信息将用于回复。请参阅我们的',
    privacyLink: '隐私政策',
    privacyEnd: '。',
    formTitle: '联系表单',
    typeLabel: '咨询类型',
    typePlaceholder: '请选择',
    typeOptions: ['一般咨询', '反馈', '更正', '其他'],
    nameLabel: '姓名',
    namePlaceholder: '例如：张三',
    emailLabel: '邮箱地址',
    emailPlaceholder: '例如：example@email.com',
    companyLabel: '公司',
    companyPlaceholder: '某某公司',
    subjectLabel: '主题',
    subjectPlaceholder: '关于文章',
    urlLabel: '页面链接',
    urlPlaceholder: 'https://...',
    urlNote: '如果适用，请提供链接。',
    messageLabel: '内容',
    messagePlaceholder: '请详细描述您的咨询。',
    agreementText: '我同意隐私政策。',
    submitBtn: '发送',
    sending: '发送中...',
    required: '必填',
    optional: '选填',
    successTitle: '已收到',
    successText: '如有需要，我们会与您联系。',
    errorText: '发送失败。',
  }
};
