// src/lib/info/ja/contactData.ts
// お問い合わせページの日本語データ

export const ja = {
  title: 'お問い合わせ',
  intro1: '24Watchinをご利用いただきありがとうございます。当サイトに関するご意見、ご感想、お問い合わせは、下記フォームよりご連絡ください。',
  intro2: '記事内容に関するご意見・ご指摘、訂正のご連絡、著作権・転載に関するお問い合わせ、広告掲載・提携に関するご相談などを受け付けています。',
  beforeTitle: 'お問い合わせの前にご確認ください',
  before1: 'お問い合わせの内容、件数、確認状況その他の事情により、回答までお時間をいただく場合や、回答を差し上げられない場合があります。',
  before2: '土曜、日曜、祝日、年末年始にいただいたお問い合わせは、翌営業日以降の確認となる場合があります。',
  before3: '当サイトからの回答内容について、無断で転載、引用、再配布することはご遠慮ください。',
  before4: '営業・勧誘・宣伝のみを目的とした送信については、回答いたしかねる場合があります。',
  privacyTitle: '個人情報の取り扱いについて',
  privacyText: 'お問い合わせフォームにご入力いただいた情報は、お問い合わせへの対応、内容の確認、必要なご連絡その他これらに付随する目的のために利用します。詳細については',
  privacyLink: 'プライバシーポリシー',
  privacyEnd: 'をご確認ください。',
  formTitle: 'お問い合わせフォーム',
  typeLabel: 'お問い合わせの種類',
  typePlaceholder: '選択してください',
  typeOptions: ['記事内容に関するご意見・ご指摘', '訂正のご連絡', '著作権・転載に関するお問い合わせ', '広告掲載・提携に関するご相談', 'その他'],
  nameLabel: 'お名前',
  namePlaceholder: '例：山田 太郎',
  emailLabel: '連絡可能なメールアドレス',
  emailPlaceholder: '例：example@email.com',
  companyLabel: '会社名・団体名',
  companyPlaceholder: '例：株式会社〇〇',
  subjectLabel: '件名',
  subjectPlaceholder: '例：記事について',
  urlLabel: '対象ページURL',
  urlPlaceholder: '例：https://24watchin.com/...',
  urlNote: '記事やページについてのお問い合わせの場合は、該当URLをご記入ください。',
  messageLabel: 'お問い合わせ内容',
  messagePlaceholder: 'できるだけ具体的にご記入ください。',
  agreementText: 'ご入力いただいた情報の取り扱いについて、プライバシーポリシーを確認し、同意します。',
  submitBtn: '送信',
  sending: '送信中...',
  required: '必須',
  optional: '任意',
  successTitle: 'お問い合わせを受け付けました。',
  successText: '内容を確認のうえ、必要に応じてご連絡いたします。',
  errorText: '送信に失敗しました。時間をおいて再度お試しください。',
};
