// src/lib/info/zh-tw/contactData.ts
// 聯絡我們頁面的繁體中文數據

export const zhTW = {
  title: '聯絡我們',
  intro1: '感謝您使用 24Watchin。若您對本網站有任何意見、感想或詢問事項，請透過下列表單與我們聯絡。',
  intro2: '我們受理有關文章內容的意見與指正、更正通知、著作權與轉載相關詢問，以及廣告刊登與合作相關洽詢等事項。',
  beforeTitle: '聯絡前請先確認以下事項',
  before1: '依據詢問內容、件數、確認狀況及其他情況，我們可能需要較長時間回覆，或可能無法逐一回覆。',
  before2: '於星期六、星期日、國定假日及年末年初期間收到的詢問，可能會於下一個營業日之後再行確認。',
  before3: '對於本網站所提供的回覆內容，請勿未經授權擅自轉載、引用 or 再散布。',
  before4: '僅以營業、招攬或宣傳為目的之來信，我們可能不予回覆。',
  privacyTitle: '關於個人資料之處理',
  privacyText: '您於聯絡表單中所填寫的資訊，將用於回覆您的詢問、確認內容、必要之聯絡，以及其他附隨於前述目的之用途。詳情請參閱',
  privacyLink: '隱私權政策',
  privacyPath: '../privacy/',
  privacyEnd: '。',
  formTitle: '聯絡表單',
  typeLabel: '聯絡類型',
  typePlaceholder: '請選擇',
  typeOptions: ['關於文章內容的意見與指正', '更正通知', '關於著作權與轉載的詢問', '關於廣告刊登與合作的洽詢', '其他'],
  nameLabel: '姓名',
  namePlaceholder: '例：王小明',
  emailLabel: '可聯絡的電子郵件地址',
  emailPlaceholder: '例：example@email.com',
  companyLabel: '公司名稱／團體名稱',
  companyPlaceholder: '例：○○股份有限公司',
  subjectLabel: '主旨',
  subjectPlaceholder: '例：關於文章',
  urlLabel: '相關頁面 URL',
  urlPlaceholder: '例：https://24watchin.com/...',
  urlNote: '如為針對文章或頁面的詢問，請填寫相關 URL。',
  messageLabel: '詢問內容',
  messagePlaceholder: '請盡可能具體填寫。',
  agreementText: '關於您所填寫資訊之處理方式，本人已確認隱私權政策，並表示同意。',
  submitBtn: '送出',
  sending: '傳送中...',
  required: '必填',
  optional: '選填',
  successTitle: '已收到您的詢問。',
  successText: '我們將在確認內容後，視需要與您聯絡。',
  errorText: '傳送失敗。請稍後再試。',
};
