// src/lib/info/de/contactData.ts
// Daten auf Deutsch für die Kontaktseite

export const de = {
  title: 'Kontakt',
  intro1: 'Vielen Dank, dass Sie 24Watchin nutzen. Wenn Sie Fragen, Anregungen oder Feedback zu unserer Website haben, kontaktieren Sie uns bitte über das untenstehende Formular.',
  intro2: 'Wir nehmen Anfragen zu Artikeln und Inhalten, Hinweise auf Fehler oder Korrekturen, Anfragen zu Urheberrechten und Wiederveröffentlichungen sowie Anfragen zu Werbung und Kooperationen entgegen.',
  beforeTitle: 'Bitte beachten Sie vor Ihrer Anfrage Folgendes',
  before1: 'Je nach Inhalt, Anzahl und Bearbeitungsstand der Anfragen sowie sonstigen Umständen kann die Beantwortung einige Zeit in Anspruch nehmen oder im Einzelfall nicht erfolgen.',
  before2: 'Anfragen, die an Samstagen, Sonntagen, gesetzlichen Feiertagen oder zum Jahreswechsel eingehen, werden gegebenenfalls erst ab dem nächsten Werktag bearbeitet.',
  before3: 'Wir bitten Sie, unsere Antworten ohne vorherige Zustimmung nicht zu vervielfältigen, zu zitieren oder weiterzuverbreiten.',
  before4: 'Nachrichten, die ausschließlich Werbe-, Akquise- oder Verkaufszwecken dienen, werden gegebenenfalls nicht beantwortet.',
  privacyTitle: 'Umgang mit personenbezogenen Daten',
  privacyText: 'Die im Kontaktformular eingegebenen Informationen werden zur Bearbeitung Ihrer Anfrage, zur Prüfung des Inhalts, für erforderliche Rückfragen sowie für sonstige damit zusammenhängende Zwecke verwendet. Weitere Einzelheiten entnehmen Sie bitte unserer ',
  privacyLink: 'Datenschutzerklärung',
  privacyPath: '../privacy/',
  privacyEnd: '.',
  formTitle: 'Kontaktformular',
  typeLabel: 'Art der Anfrage',
  typePlaceholder: 'Bitte auswählen',
  typeOptions: [
    'Feedback oder Hinweise zum Artikelinhalt',
    'Mitteilung über eine Korrektur',
    'Anfrage zu Urheberrecht oder Wiederveröffentlichung',
    'Anfrage zu Werbung oder Kooperation',
    'Sonstiges'
  ],
  nameLabel: 'Name',
  namePlaceholder: 'z. B. Max Mustermann',
  emailLabel: 'E-Mail-Adresse',
  emailPlaceholder: 'z. B. max.mustermann@example.com',
  companyLabel: 'Firma / Organisation',
  companyPlaceholder: 'z. B. Musterfirma GmbH',
  subjectLabel: 'Betreff',
  subjectPlaceholder: 'z. B. Anfrage zu einem Artikel',
  urlLabel: 'URL der betreffenden Seite',
  urlPlaceholder: 'z. B. https://24watchin.com/...',
  urlNote: 'Wenn sich Ihre Anfrage auf einen bestimmten Artikel oder eine bestimmte Seite bezieht, geben Sie bitte die entsprechende URL an.',
  messageLabel: 'Nachricht',
  messagePlaceholder: 'Bitte beschreiben Sie Ihr Anliegen so detailliert wie möglich.',
  agreementText: 'Ich habe die Datenschutzerklärung zur Kenntnis genommen und stimme der Verarbeitung meiner Daten zu.',
  submitBtn: 'Absenden',
  sending: 'Wird gesendet...',
  required: 'Pflichtfeld',
  optional: 'Optional',
  successTitle: 'Ihre Anfrage wurde erfolgreich übermittelt.',
  successText: 'Wir werden uns nach Prüfung des Inhalts gegebenenfalls bei Ihnen melden.',
  errorText: 'Fehler beim Senden. Bitte versuchen Sie es später erneut.',
};
