// src/lib/info/fr/contactData.ts
// Données en français pour la page de contact

export const fr = {
  title: 'Contact',
  intro1: "Merci d'utiliser 24Watchin. Pour toute question, remarque ou commentaire concernant notre site, veuillez nous contacter via le formulaire ci-dessous.",
  intro2: "Nous acceptons les remarques et signalements concernant le contenu des articles, les demandes de correction, les demandes relatives aux droits d'auteur et à la republication, ainsi que les consultations concernant la publicité et les partenariats.",
  beforeTitle: 'Veuillez vérifier les points suivants avant de nous contacter',
  before1: "Selon la nature de votre demande, le nombre de demandes reçues, l'état de vérification ou d'autres circonstances, il se peut qu'un certain délai soit nécessaire avant de vous répondre, ou que nous ne soyons pas en mesure de vous répondre.",
  before2: "Les demandes reçues le samedi, le dimanche, les jours fériés ou pendant les vacances de fin d'année et du Nouvel An peuvent être examinées à partir du jour ouvrable suivant.",
  before3: "Nous vous prions de vous abstenir de reproduire, citer ou redistribuer sans autorisation le contenu de notre réponse.",
  before4: "Nous pourrions ne pas être en mesure de répondre aux messages envoyés uniquement à des fins commerciales, de sollicitation ou de promotion.",
  privacyTitle: 'Traitement des données personnelles',
  privacyText: 'Les informations saisies dans le formulaire de contact sont utilisées pour répondre à votre demande, en vérifier le contenu, vous contacter si nécessaire, ainsi que pour toute finalité connexe à ces objectifs. Pour plus de détails, veuillez consulter notre ',
  privacyLink: 'Politique de confidentialité',
  privacyPath: '../privacy/',
  privacyEnd: '.',
  formTitle: 'Formulaire de contact',
  typeLabel: 'Type de demande',
  typePlaceholder: 'Sélectionnez une option',
  typeOptions: [
    'Avis ou remarques sur le contenu de l’article',
    'Demande de correction',
    'Question sur les droits d’auteur ou la republication',
    'Demande concernant la publicité ou un partenariat',
    'Autre'
  ],
  nameLabel: 'Nom',
  namePlaceholder: 'Exemple : Jean Dupont',
  emailLabel: 'Adresse e-mail de contact',
  emailPlaceholder: 'Exemple : example@email.com',
  companyLabel: "Nom de l'entreprise / de l'organisation",
  companyPlaceholder: 'Exemple : Société Martin',
  subjectLabel: 'Objet',
  subjectPlaceholder: 'Exemple : Concernant un article',
  urlLabel: 'URL de la page concernée',
  urlPlaceholder: 'Exemple : https://24watchin.com/...',
  urlNote: "Si votre demande concerne un article ou une page, veuillez indiquer l'URL correspondante.",
  messageLabel: 'Contenu de la demande',
  messagePlaceholder: 'Veuillez décrire votre demande aussi précisément que possible.',
  agreementText: "Concernant le traitement des informations que vous avez fournies, j'ai vérifié la politique de confidentialité et je donne mon consentement.",
  submitBtn: 'Envoyer',
  sending: 'Envoi en cours...',
  required: 'Obligatoire',
  optional: 'Facultatif',
  successTitle: 'Votre demande a bien été reçue.',
  successText: 'Nous examinerons votre demande et vous contacterons si nécessaire.',
  errorText: "Échec de l'envoi. Veuillez réessayer plus tard.",
};
