// src/lib/info/es/contactData.ts
// Datos en español para la página de contacto

export const es = {
  title: 'Contacto',
  intro1: 'Gracias por visitar 24Watchin. Si desea enviarnos una consulta, una opinión o cualquier comentario relacionado con este sitio web, puede hacerlo a través del siguiente formulario.',
  intro2: 'Atendemos consultas sobre el contenido de los artículos, solicitudes de corrección, cuestiones relacionadas con derechos de autor y reproducción de contenidos, así como propuestas de publicidad o colaboración.',
  beforeTitle: 'Antes de contactar con nosotros',
  before1: 'En función del contenido de la consulta, del volumen de mensajes recibidos, del proceso de comprobación u otras circunstancias, es posible que tardemos un tiempo en responder o que no podamos ofrecer una respuesta.',
  before2: 'Las consultas enviadas los sábados, domingos, festivos o durante el periodo de fin de año y Año Nuevo podrán revisarse a partir del siguiente día laborable.',
  before3: 'Le rogamos que no reproduzca, cite ni redistribuya sin autorización el contenido de nuestras respuestas.',
  before4: 'Es posible que no respondamos a mensajes enviados únicamente con fines comerciales, publicitarios o promocionales.',
  privacyTitle: 'Tratamiento de los datos personales',
  privacyText: 'La información facilitada a través del formulario de contacto se utilizará para atender su consulta, verificar su contenido, ponernos en contacto con usted cuando sea necesario y para cualquier gestión relacionada con dicha consulta. Para más información, consulte nuestra ',
  privacyLink: 'Política de privacidad',
  privacyPath: '../privacy/',
  privacyEnd: '.',
  formTitle: 'Formulario de contacto',
  typeLabel: 'Tipo de consulta',
  typePlaceholder: 'Seleccione una opción',
  typeOptions: [
    'Comentarios u observaciones sobre el contenido del artículo',
    'Solicitud de corrección',
    'Consulta sobre derechos de autor o reproducción',
    'Consulta sobre publicidad o colaboración',
    'Otros'
  ],
  nameLabel: 'Nombre y apellidos',
  namePlaceholder: 'Ejemplo: Juan Pérez',
  emailLabel: 'Correo electrónico de contacto',
  emailPlaceholder: 'Ejemplo: nombre@correo.com',
  companyLabel: 'Empresa o entidad',
  companyPlaceholder: 'Ejemplo: Empresa Ejemplo, S.A.',
  subjectLabel: 'Asunto',
  subjectPlaceholder: 'Ejemplo: Consulta sobre un artículo',
  urlLabel: 'URL de la página',
  urlPlaceholder: 'Ejemplo: https://24watchin.com/...',
  urlNote: 'Si su consulta está relacionada con un artículo o con una página concreta, indique la URL correspondiente.',
  messageLabel: 'Mensaje',
  messagePlaceholder: 'Por favor, describa su consulta con el mayor detalle posible.',
  agreementText: 'He leído y acepto la Política de privacidad y consiento el tratamiento de mis datos.',
  submitBtn: 'Enviar',
  sending: 'Enviando...',
  required: 'Obligatorio',
  optional: 'Opcional',
  successTitle: 'Hemos recibido su consulta.',
  successText: 'Revisaremos el contenido y nos pondremos en contacto con usted si es necesario.',
  errorText: 'Se ha producido un error al enviar el formulario. Por favor, inténtelo de nuevo más tarde.',
};
